// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DetailsContainerController from "./details_container_controller"
import SiteSearchController from "./site_search_controller"

application.register("details-container", DetailsContainerController)
application.register("site-search", SiteSearchController)
