inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'

Rails:
  Enabled: true

Layout/LineLength:
  Max: 120
  Exclude:
    - 'app/models/spotlight/dor/indexer.rb'
    - 'lib/traject/dor_config.rb'
    - 'spec/features/indexing_integration_spec.rb'
    - 'spec/models/spotlight/dor/indexer_spec.rb'
    - 'spec/features/bibliography_formatting_spec.rb'

Metrics/ModuleLength:
  Exclude:
    - "app/helpers/search_across_helper.rb"

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%w': '()'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/SymbolArray:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/controllers/search_across_controller.rb'

Capybara/FeatureMethods:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

RSpec/ExampleLength:
  Max: 10
  Exclude:
    - 'spec/features/indexing_integration_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/controllers/search_across_controller.rb'
    - 'app/models/spotlight/dor/indexer.rb'
    - 'spec/**/*'

Performance/RedundantBlockCall:
  Exclude:
    - 'lib/traject/macros/**/*'
