inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'

Rails:
  Enabled: true

Metrics/BlockLength:
  Exclude:
  - 'spec/models/spotlight/dor/indexer_spec.rb'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'app/models/spotlight/dor/indexer.rb'
    - 'spec/features/indexing_integration_spec.rb'
    - 'spec/models/spotlight/dor/indexer_spec.rb'
    - 'spec/features/bibliography_formatting_spec.rb'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%w': '()'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/SymbolArray:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Capybara/FeatureMethods:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

RSpec/ExampleLength:
  Max: 10
  Exclude:
    - 'spec/features/indexing_integration_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/models/spotlight/dor/indexer.rb'
    - 'spec/**/*'

Performance/RedundantBlockCall:
  Exclude:
    - 'lib/traject/macros/**/*'
