inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'app/models/spotlight/dor/indexer.rb'
    - 'spec/models/spotlight/dor/indexer_spec.rb'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

RSpec/NamedSubject:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

RSpec/ExampleLength:
  Max: 7
