import 'leaflet'
import 'leaflet-sidebar/src/L.Control.Sidebar'
import 'blacklight-heatmaps/vendor/assets/javascripts/leaflet_solr_heatmap'
import 'blacklight-heatmaps'
import './blacklight_heatmaps_overrides'
